version: '3'
services:
  geek-frontend:
    image: frontend:latest
    ports:
      - 8081:80

  inter-web :
    image: inter-web:latest
    ports:
      - 8080
    depends_on:
      - db
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/entrypoint.sh"

  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: