server:
  port: 2021
spring:
  datasource:
    url: jdbc:mysql://db:3306/inter?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
jpa:
  show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
