server:
  port: 2021
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inter
    username: root
    password: root
jpa:
  show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
